# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1468, 773)
        MainWindow.setStyleSheet("QGroupBox::title{\n"
"    left: 7px\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(15, 15, 15, 15)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonMainStartAcquisition = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMainStartAcquisition.sizePolicy().hasHeightForWidth())
        self.buttonMainStartAcquisition.setSizePolicy(sizePolicy)
        self.buttonMainStartAcquisition.setToolTip("")
        self.buttonMainStartAcquisition.setObjectName("buttonMainStartAcquisition")
        self.horizontalLayout_2.addWidget(self.buttonMainStartAcquisition)
        self.mainStatus = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainStatus.sizePolicy().hasHeightForWidth())
        self.mainStatus.setSizePolicy(sizePolicy)
        self.mainStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.mainStatus.setReadOnly(True)
        self.mainStatus.setObjectName("mainStatus")
        self.horizontalLayout_2.addWidget(self.mainStatus)
        self.buttonMainShutdown = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMainShutdown.sizePolicy().hasHeightForWidth())
        self.buttonMainShutdown.setSizePolicy(sizePolicy)
        self.buttonMainShutdown.setObjectName("buttonMainShutdown")
        self.horizontalLayout_2.addWidget(self.buttonMainShutdown)
        self.horizontalLayout_2.setStretch(0, 10)
        self.horizontalLayout_2.setStretch(1, 80)
        self.horizontalLayout_2.setStretch(2, 10)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setContentsMargins(6, -1, 6, -1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.camtrackUpper1 = QtWidgets.QSpinBox(self.groupBox_4)
        self.camtrackUpper1.setAlignment(QtCore.Qt.AlignCenter)
        self.camtrackUpper1.setMinimum(1)
        self.camtrackUpper1.setMaximum(1024)
        self.camtrackUpper1.setProperty("value", 198)
        self.camtrackUpper1.setObjectName("camtrackUpper1")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.camtrackUpper1)
        self.buttonCamtrackUpdate = QtWidgets.QPushButton(self.groupBox_4)
        self.buttonCamtrackUpdate.setObjectName("buttonCamtrackUpdate")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.buttonCamtrackUpdate)
        self.camtrackLower1 = QtWidgets.QSpinBox(self.groupBox_4)
        self.camtrackLower1.setAlignment(QtCore.Qt.AlignCenter)
        self.camtrackLower1.setMinimum(1)
        self.camtrackLower1.setMaximum(1024)
        self.camtrackLower1.setProperty("value", 165)
        self.camtrackLower1.setObjectName("camtrackLower1")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.camtrackLower1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.gridLayout_3.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setContentsMargins(6, -1, 6, -1)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.buttonCamtrackView = QtWidgets.QPushButton(self.groupBox_4)
        self.buttonCamtrackView.setObjectName("buttonCamtrackView")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.buttonCamtrackView)
        self.camtrackUpper2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.camtrackUpper2.setAlignment(QtCore.Qt.AlignCenter)
        self.camtrackUpper2.setMinimum(1)
        self.camtrackUpper2.setMaximum(1024)
        self.camtrackUpper2.setProperty("value", 244)
        self.camtrackUpper2.setObjectName("camtrackUpper2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.camtrackUpper2)
        self.camtrackLower2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.camtrackLower2.setAlignment(QtCore.Qt.AlignCenter)
        self.camtrackLower2.setMinimum(1)
        self.camtrackLower2.setMaximum(1024)
        self.camtrackLower2.setProperty("value", 211)
        self.camtrackLower2.setObjectName("camtrackLower2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.camtrackLower2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.gridLayout_3.addLayout(self.formLayout_4, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 47)
        self.gridLayout_3.setColumnStretch(1, 6)
        self.gridLayout_3.setColumnStretch(2, 47)
        self.gridLayout_4.addWidget(self.groupBox_4, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 3, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 3, 5, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_8.setContentsMargins(6, -1, 6, -1)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setObjectName("label_7")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.buttonSpectralStart = QtWidgets.QPushButton(self.groupBox_5)
        self.buttonSpectralStart.setObjectName("buttonSpectralStart")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.buttonSpectralStart)
        self.spectralBackgroundFrames = QtWidgets.QSpinBox(self.groupBox_5)
        self.spectralBackgroundFrames.setAlignment(QtCore.Qt.AlignCenter)
        self.spectralBackgroundFrames.setMinimum(1)
        self.spectralBackgroundFrames.setMaximum(999)
        self.spectralBackgroundFrames.setProperty("value", 50)
        self.spectralBackgroundFrames.setObjectName("spectralBackgroundFrames")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spectralBackgroundFrames)
        self.spectralFrames = QtWidgets.QSpinBox(self.groupBox_5)
        self.spectralFrames.setAlignment(QtCore.Qt.AlignCenter)
        self.spectralFrames.setMaximum(999)
        self.spectralFrames.setProperty("value", 100)
        self.spectralFrames.setObjectName("spectralFrames")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spectralFrames)
        self.gridLayout_8.addLayout(self.formLayout_8, 0, 2, 1, 1)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_7.setContentsMargins(6, -1, 6, -1)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setObjectName("label_6")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.buttonSpectralUpdate = QtWidgets.QPushButton(self.groupBox_5)
        self.buttonSpectralUpdate.setObjectName("buttonSpectralUpdate")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.buttonSpectralUpdate)
        self.spectralRequiredTime = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spectralRequiredTime.setAlignment(QtCore.Qt.AlignCenter)
        self.spectralRequiredTime.setMinimum(0.01)
        self.spectralRequiredTime.setMaximum(10.0)
        self.spectralRequiredTime.setSingleStep(0.01)
        self.spectralRequiredTime.setProperty("value", 0.05)
        self.spectralRequiredTime.setObjectName("spectralRequiredTime")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spectralRequiredTime)
        self.spectralActualTime = QtWidgets.QLineEdit(self.groupBox_5)
        self.spectralActualTime.setAlignment(QtCore.Qt.AlignCenter)
        self.spectralActualTime.setReadOnly(True)
        self.spectralActualTime.setObjectName("spectralActualTime")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spectralActualTime)
        self.gridLayout_8.addLayout(self.formLayout_7, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 0, 1, 1, 1)
        self.gridLayout_8.setColumnStretch(0, 47)
        self.gridLayout_8.setColumnStretch(1, 6)
        self.gridLayout_8.setColumnStretch(2, 47)
        self.gridLayout_4.addWidget(self.groupBox_5, 1, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.buttonDialogsDifference = QtWidgets.QPushButton(self.groupBox)
        self.buttonDialogsDifference.setObjectName("buttonDialogsDifference")
        self.gridLayout_9.addWidget(self.buttonDialogsDifference, 0, 0, 1, 1)
        self.buttonDialogsSum = QtWidgets.QPushButton(self.groupBox)
        self.buttonDialogsSum.setObjectName("buttonDialogsSum")
        self.gridLayout_9.addWidget(self.buttonDialogsSum, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 1, 6, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.buttonHyperspectralTime = QtWidgets.QPushButton(self.groupBox_7)
        self.buttonHyperspectralTime.setObjectName("buttonHyperspectralTime")
        self.horizontalLayout_7.addWidget(self.buttonHyperspectralTime)
        self.buttonHyperspectralStart = QtWidgets.QPushButton(self.groupBox_7)
        self.buttonHyperspectralStart.setObjectName("buttonHyperspectralStart")
        self.horizontalLayout_7.addWidget(self.buttonHyperspectralStart)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 1, 0, 1, 2)
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setContentsMargins(6, -1, 6, -1)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setObjectName("label_13")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setObjectName("label_14")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setObjectName("label_15")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setObjectName("label_16")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.hyperspectralBackgroundFrames = QtWidgets.QSpinBox(self.groupBox_7)
        self.hyperspectralBackgroundFrames.setAlignment(QtCore.Qt.AlignCenter)
        self.hyperspectralBackgroundFrames.setMinimum(1)
        self.hyperspectralBackgroundFrames.setMaximum(999)
        self.hyperspectralBackgroundFrames.setProperty("value", 50)
        self.hyperspectralBackgroundFrames.setObjectName("hyperspectralBackgroundFrames")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hyperspectralBackgroundFrames)
        self.hyperspectralXYStep = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.hyperspectralXYStep.setAlignment(QtCore.Qt.AlignCenter)
        self.hyperspectralXYStep.setMinimum(0.01)
        self.hyperspectralXYStep.setMaximum(1.0)
        self.hyperspectralXYStep.setSingleStep(0.01)
        self.hyperspectralXYStep.setProperty("value", 0.3)
        self.hyperspectralXYStep.setObjectName("hyperspectralXYStep")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hyperspectralXYStep)
        self.hyperspectralZStep = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.hyperspectralZStep.setAlignment(QtCore.Qt.AlignCenter)
        self.hyperspectralZStep.setMinimum(0.01)
        self.hyperspectralZStep.setMaximum(1.0)
        self.hyperspectralZStep.setSingleStep(0.01)
        self.hyperspectralZStep.setProperty("value", 0.5)
        self.hyperspectralZStep.setObjectName("hyperspectralZStep")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.hyperspectralZStep)
        self.hyperspectralEstTime = QtWidgets.QLineEdit(self.groupBox_7)
        self.hyperspectralEstTime.setAlignment(QtCore.Qt.AlignCenter)
        self.hyperspectralEstTime.setReadOnly(True)
        self.hyperspectralEstTime.setObjectName("hyperspectralEstTime")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.hyperspectralEstTime)
        self.gridLayout_7.addLayout(self.formLayout_10, 0, 1, 1, 1)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setContentsMargins(6, -1, 6, -1)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setObjectName("label_9")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setObjectName("label_10")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setObjectName("label_11")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setObjectName("label_12")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.hyperspectralRequiredTime = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.hyperspectralRequiredTime.setAlignment(QtCore.Qt.AlignCenter)
        self.hyperspectralRequiredTime.setMinimum(0.01)
        self.hyperspectralRequiredTime.setMaximum(10.0)
        self.hyperspectralRequiredTime.setSingleStep(0.01)
        self.hyperspectralRequiredTime.setProperty("value", 0.05)
        self.hyperspectralRequiredTime.setObjectName("hyperspectralRequiredTime")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hyperspectralRequiredTime)
        self.hyperspectralXPix = QtWidgets.QSpinBox(self.groupBox_7)
        self.hyperspectralXPix.setAlignment(QtCore.Qt.AlignCenter)
        self.hyperspectralXPix.setMinimum(1)
        self.hyperspectralXPix.setMaximum(999)
        self.hyperspectralXPix.setProperty("value", 100)
        self.hyperspectralXPix.setObjectName("hyperspectralXPix")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hyperspectralXPix)
        self.hyperspectralYPix = QtWidgets.QSpinBox(self.groupBox_7)
        self.hyperspectralYPix.setAlignment(QtCore.Qt.AlignCenter)
        self.hyperspectralYPix.setMinimum(1)
        self.hyperspectralYPix.setMaximum(999)
        self.hyperspectralYPix.setProperty("value", 100)
        self.hyperspectralYPix.setObjectName("hyperspectralYPix")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.hyperspectralYPix)
        self.hyperspectralZPix = QtWidgets.QSpinBox(self.groupBox_7)
        self.hyperspectralZPix.setAlignment(QtCore.Qt.AlignCenter)
        self.hyperspectralZPix.setMinimum(1)
        self.hyperspectralZPix.setMaximum(999)
        self.hyperspectralZPix.setProperty("value", 1)
        self.hyperspectralZPix.setObjectName("hyperspectralZPix")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.hyperspectralZPix)
        self.gridLayout_7.addLayout(self.formLayout_9, 0, 0, 1, 1)
        self.gridLayout_7.setColumnStretch(0, 50)
        self.gridLayout_7.setColumnStretch(1, 50)
        self.gridLayout_7.setRowStretch(0, 80)
        self.gridLayout_7.setRowStretch(1, 20)
        self.gridLayout_4.addWidget(self.groupBox_7, 3, 2, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.eventLogger = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.eventLogger.setReadOnly(True)
        self.eventLogger.setObjectName("eventLogger")
        self.gridLayout_6.addWidget(self.eventLogger, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_6, 3, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setObjectName("groupBox_9")
        self.formLayout_14 = QtWidgets.QFormLayout(self.groupBox_9)
        self.formLayout_14.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_14.setHorizontalSpacing(1)
        self.formLayout_14.setObjectName("formLayout_14")
        self.grating150 = QtWidgets.QRadioButton(self.groupBox_9)
        self.grating150.setChecked(True)
        self.grating150.setObjectName("grating150")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.grating150)
        self.label_20 = QtWidgets.QLabel(self.groupBox_9)
        self.label_20.setObjectName("label_20")
        self.formLayout_14.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.gratingRequiredWavelength = QtWidgets.QSpinBox(self.groupBox_9)
        self.gratingRequiredWavelength.setAlignment(QtCore.Qt.AlignCenter)
        self.gratingRequiredWavelength.setMinimum(300)
        self.gratingRequiredWavelength.setMaximum(999)
        self.gratingRequiredWavelength.setProperty("value", 682)
        self.gratingRequiredWavelength.setObjectName("gratingRequiredWavelength")
        self.formLayout_14.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gratingRequiredWavelength)
        self.label_17 = QtWidgets.QLabel(self.groupBox_9)
        self.label_17.setObjectName("label_17")
        self.formLayout_14.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.gratingActualWavelength = QtWidgets.QLineEdit(self.groupBox_9)
        self.gratingActualWavelength.setAlignment(QtCore.Qt.AlignCenter)
        self.gratingActualWavelength.setReadOnly(True)
        self.gratingActualWavelength.setObjectName("gratingActualWavelength")
        self.formLayout_14.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gratingActualWavelength)
        self.buttonGratingUpdate = QtWidgets.QPushButton(self.groupBox_9)
        self.buttonGratingUpdate.setObjectName("buttonGratingUpdate")
        self.formLayout_14.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.buttonGratingUpdate)
        self.buttonGratingState = QtWidgets.QPushButton(self.groupBox_9)
        self.buttonGratingState.setObjectName("buttonGratingState")
        self.formLayout_14.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.buttonGratingState)
        self.grating600 = QtWidgets.QRadioButton(self.groupBox_9)
        self.grating600.setObjectName("grating600")
        self.formLayout_14.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.grating600)
        self.gridLayout_4.addWidget(self.groupBox_9, 3, 4, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4.addWidget(self.groupBox_2, 3, 6, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setObjectName("groupBox_10")
        self.formLayout_13 = QtWidgets.QFormLayout(self.groupBox_10)
        self.formLayout_13.setObjectName("formLayout_13")
        self.buttonCameratempCooler = QtWidgets.QPushButton(self.groupBox_10)
        self.buttonCameratempCooler.setObjectName("buttonCameratempCooler")
        self.formLayout_13.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.buttonCameratempCooler)
        self.label_19 = QtWidgets.QLabel(self.groupBox_10)
        self.label_19.setObjectName("label_19")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.cameratempRequiredTemp = QtWidgets.QSpinBox(self.groupBox_10)
        self.cameratempRequiredTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.cameratempRequiredTemp.setMinimum(-100)
        self.cameratempRequiredTemp.setMaximum(30)
        self.cameratempRequiredTemp.setProperty("value", -80)
        self.cameratempRequiredTemp.setObjectName("cameratempRequiredTemp")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cameratempRequiredTemp)
        self.cameratempActualTemp = QtWidgets.QLineEdit(self.groupBox_10)
        self.cameratempActualTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.cameratempActualTemp.setReadOnly(True)
        self.cameratempActualTemp.setObjectName("cameratempActualTemp")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.cameratempActualTemp)
        self.gridLayout_4.addWidget(self.groupBox_10, 1, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 3, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 2, 2, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 45)
        self.gridLayout_4.setColumnStretch(2, 25)
        self.gridLayout_4.setColumnStretch(4, 15)
        self.gridLayout_4.setColumnStretch(6, 15)
        self.horizontalLayout_3.addLayout(self.gridLayout_4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.specwinPrevious = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.specwinPrevious.sizePolicy().hasHeightForWidth())
        self.specwinPrevious.setSizePolicy(sizePolicy)
        self.specwinPrevious.setObjectName("specwinPrevious")
        self.gridLayout_5.addWidget(self.specwinPrevious, 0, 1, 1, 1)
        self.imagewinMain = ImageView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagewinMain.sizePolicy().hasHeightForWidth())
        self.imagewinMain.setSizePolicy(sizePolicy)
        self.imagewinMain.setObjectName("imagewinMain")
        self.gridLayout_5.addWidget(self.imagewinMain, 0, 0, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 40)
        self.gridLayout_5.setColumnStretch(1, 60)
        self.gridLayout_5.setRowStretch(0, 98)
        self.horizontalLayout_3.addLayout(self.gridLayout_5)
        self.horizontalLayout_3.setStretch(0, 45)
        self.horizontalLayout_3.setStretch(1, 55)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 1, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.specwinMain = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.specwinMain.sizePolicy().hasHeightForWidth())
        self.specwinMain.setSizePolicy(sizePolicy)
        self.specwinMain.setObjectName("specwinMain")
        self.verticalLayout_3.addWidget(self.specwinMain)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.setStretch(0, 95)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 1, 1, 2)
        self.progressbar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressbar.sizePolicy().hasHeightForWidth())
        self.progressbar.setSizePolicy(sizePolicy)
        self.progressbar.setProperty("value", 64)
        self.progressbar.setObjectName("progressbar")
        self.gridLayout.addWidget(self.progressbar, 4, 1, 1, 2)
        self.gridLayout.setRowStretch(0, 66)
        self.gridLayout.setRowStretch(1, 4)
        self.gridLayout.setRowStretch(3, 30)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1468, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_Hyperspectral_Viewer = QtWidgets.QAction(MainWindow)
        self.actionOpen_Hyperspectral_Viewer.setObjectName("actionOpen_Hyperspectral_Viewer")
        self.actionOpen_Sum_Spectrum = QtWidgets.QAction(MainWindow)
        self.actionOpen_Sum_Spectrum.setObjectName("actionOpen_Sum_Spectrum")
        self.actionOpen_Difference_Spectrum = QtWidgets.QAction(MainWindow)
        self.actionOpen_Difference_Spectrum.setObjectName("actionOpen_Difference_Spectrum")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen_Data_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Data_Folder.setObjectName("actionOpen_Data_Folder")
        self.menuFile.addAction(self.actionOpen_Data_Folder)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.specwinMain, self.buttonMainStartAcquisition)
        MainWindow.setTabOrder(self.buttonMainStartAcquisition, self.mainStatus)
        MainWindow.setTabOrder(self.mainStatus, self.buttonMainShutdown)
        MainWindow.setTabOrder(self.buttonMainShutdown, self.camtrackLower1)
        MainWindow.setTabOrder(self.camtrackLower1, self.camtrackUpper1)
        MainWindow.setTabOrder(self.camtrackUpper1, self.camtrackLower2)
        MainWindow.setTabOrder(self.camtrackLower2, self.camtrackUpper2)
        MainWindow.setTabOrder(self.camtrackUpper2, self.buttonCamtrackUpdate)
        MainWindow.setTabOrder(self.buttonCamtrackUpdate, self.buttonCamtrackView)
        MainWindow.setTabOrder(self.buttonCamtrackView, self.spectralRequiredTime)
        MainWindow.setTabOrder(self.spectralRequiredTime, self.spectralBackgroundFrames)
        MainWindow.setTabOrder(self.spectralBackgroundFrames, self.spectralActualTime)
        MainWindow.setTabOrder(self.spectralActualTime, self.spectralFrames)
        MainWindow.setTabOrder(self.spectralFrames, self.buttonSpectralUpdate)
        MainWindow.setTabOrder(self.buttonSpectralUpdate, self.buttonSpectralStart)
        MainWindow.setTabOrder(self.buttonSpectralStart, self.cameratempRequiredTemp)
        MainWindow.setTabOrder(self.cameratempRequiredTemp, self.cameratempActualTemp)
        MainWindow.setTabOrder(self.cameratempActualTemp, self.buttonCameratempCooler)
        MainWindow.setTabOrder(self.buttonCameratempCooler, self.buttonDialogsDifference)
        MainWindow.setTabOrder(self.buttonDialogsDifference, self.buttonDialogsSum)
        MainWindow.setTabOrder(self.buttonDialogsSum, self.eventLogger)
        MainWindow.setTabOrder(self.eventLogger, self.hyperspectralRequiredTime)
        MainWindow.setTabOrder(self.hyperspectralRequiredTime, self.hyperspectralBackgroundFrames)
        MainWindow.setTabOrder(self.hyperspectralBackgroundFrames, self.hyperspectralXPix)
        MainWindow.setTabOrder(self.hyperspectralXPix, self.hyperspectralXYStep)
        MainWindow.setTabOrder(self.hyperspectralXYStep, self.hyperspectralYPix)
        MainWindow.setTabOrder(self.hyperspectralYPix, self.hyperspectralZStep)
        MainWindow.setTabOrder(self.hyperspectralZStep, self.hyperspectralZPix)
        MainWindow.setTabOrder(self.hyperspectralZPix, self.hyperspectralEstTime)
        MainWindow.setTabOrder(self.hyperspectralEstTime, self.buttonHyperspectralTime)
        MainWindow.setTabOrder(self.buttonHyperspectralTime, self.buttonHyperspectralStart)
        MainWindow.setTabOrder(self.buttonHyperspectralStart, self.grating150)
        MainWindow.setTabOrder(self.grating150, self.grating600)
        MainWindow.setTabOrder(self.grating600, self.gratingRequiredWavelength)
        MainWindow.setTabOrder(self.gratingRequiredWavelength, self.gratingActualWavelength)
        MainWindow.setTabOrder(self.gratingActualWavelength, self.buttonGratingUpdate)
        MainWindow.setTabOrder(self.buttonGratingUpdate, self.buttonGratingState)
        MainWindow.setTabOrder(self.buttonGratingState, self.imagewinMain)
        MainWindow.setTabOrder(self.imagewinMain, self.specwinPrevious)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonMainStartAcquisition.setText(_translate("MainWindow", "Start Acquisition"))
        self.buttonMainShutdown.setText(_translate("MainWindow", "Shut Down"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Camera Track Options"))
        self.label.setText(_translate("MainWindow", "Lower (1):"))
        self.buttonCamtrackUpdate.setText(_translate("MainWindow", "Update Tracks"))
        self.label_2.setText(_translate("MainWindow", "Upper (1):"))
        self.label_3.setText(_translate("MainWindow", "Lower (2):"))
        self.buttonCamtrackView.setText(_translate("MainWindow", "View CCD Tracks"))
        self.label_4.setText(_translate("MainWindow", "Upper (2):"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Spectral Acquisition"))
        self.label_7.setText(_translate("MainWindow", "Background frames:"))
        self.label_8.setText(_translate("MainWindow", "Spectral frames:"))
        self.buttonSpectralStart.setText(_translate("MainWindow", "Start Spectral Acquisition"))
        self.label_5.setText(_translate("MainWindow", "Exposure Time (s):"))
        self.label_6.setText(_translate("MainWindow", "Actual Exp. Time (s):"))
        self.buttonSpectralUpdate.setText(_translate("MainWindow", "Update Time"))
        self.groupBox.setTitle(_translate("MainWindow", "Spectra Dialogs"))
        self.buttonDialogsDifference.setText(_translate("MainWindow", "Difference\n"
"Plot"))
        self.buttonDialogsSum.setText(_translate("MainWindow", "Sum\n"
"Plot"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Hyperspectral Acquisition"))
        self.buttonHyperspectralTime.setText(_translate("MainWindow", "Update Est. Time"))
        self.buttonHyperspectralStart.setText(_translate("MainWindow", "Start Hyperspectral Acquisition"))
        self.label_13.setText(_translate("MainWindow", "Background frames: "))
        self.label_14.setText(_translate("MainWindow", "XY Step Size (μm): "))
        self.label_15.setText(_translate("MainWindow", "Z Step Size (μm):"))
        self.label_16.setText(_translate("MainWindow", "Estimated Time (min): "))
        self.label_9.setText(_translate("MainWindow", "Exposure Time (s):  "))
        self.label_10.setText(_translate("MainWindow", "No. of X Pixels:"))
        self.label_11.setText(_translate("MainWindow", "No. of Y Pixels:"))
        self.label_12.setText(_translate("MainWindow", "No. of Z Pixels:"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Event Logger"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Spectrometer Grating"))
        self.grating150.setText(_translate("MainWindow", "150 lines/mm"))
        self.label_20.setText(_translate("MainWindow", "Req. λ (nm):"))
        self.label_17.setText(_translate("MainWindow", "Actual λ (nm):"))
        self.buttonGratingUpdate.setText(_translate("MainWindow", "Update"))
        self.buttonGratingState.setText(_translate("MainWindow", "Turn Off"))
        self.grating600.setText(_translate("MainWindow", "600 lines/mm"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Plot Tools"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Camera Temperature"))
        self.buttonCameratempCooler.setText(_translate("MainWindow", "Cooler On"))
        self.label_19.setText(_translate("MainWindow", "Temp:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_Hyperspectral_Viewer.setText(_translate("MainWindow", "Open Hyperspectral Viewer"))
        self.actionOpen_Hyperspectral_Viewer.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionOpen_Sum_Spectrum.setText(_translate("MainWindow", "Open Sum Spectrum"))
        self.actionOpen_Difference_Spectrum.setText(_translate("MainWindow", "Open Difference Spectrum"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpen_Data_Folder.setText(_translate("MainWindow", "Open Data Folder"))

from pyqtgraph import ImageView, PlotWidget
